# Generated by Django 4.0.3 on 2023-04-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_studentdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentData',
            new_name='History',
        ),
    ]
