# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRL0WBJm-90teRowNuHCiZVO4fZd4UDR
"""

import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.layers import Dense, InputLayer
from tensorflow.keras.models import Sequential
from keras import regularizers

# !pip install tensorflow
def QSAR(fp):
    print(fp)
    # from google.colab import files
    # import io

    # data1 = files.upload()

    # df1 = pd.read_csv(io.BytesIO(data1['bioactivity_data_3c_pIC50_pubchem_fingerprints.csv']))

    # df1.head()

    # def QSAR(bio_act_fp, fp):
    df1 = pd.read_csv('medi/Model/bioactivity_data_3c_pIC50_pubchem_fingerprints.csv')

    # data2 = files.upload()

    # df2 = pd.read_csv(io.BytesIO(data2['df_final_3c.csv']))

    # df2.head()
    df2 = pd.read_csv("medi/Model/df_final_3c.csv")

    # df2.iloc[117]

    df1.drop(["Unnamed: 0"], axis=1, inplace=True)

    # df1.head()

    df_new = pd.concat([df1, df2["bioactivity_class"]], axis=1)
    # df_new.head()

    df_new = df_new[df_new['bioactivity_class'] != "intermediate"]

    # df_new.head()

    df_Y = df_new["bioactivity_class"]
    # df_Y.head()

    df_X = df_new.drop(["bioactivity_class"], axis=1)
    # df_X

    # Label Encoding
    encoder = LabelEncoder()
    encoder.fit(df_Y)
    new_Y = encoder.transform(df_Y)

    df_new_Y = pd.DataFrame(new_Y, columns=["bioactivity_class"])

    # df_new_Y.head()


    train_X, test_X, train_Y, test_Y = train_test_split(
        df_X, df_new_Y, test_size=0.1, random_state=42)

    # train_X.head(10)

    # train_Y.head()

    # define network architecture
    MLP = Sequential()
    MLP.add(InputLayer(input_shape=(882, ))) # input layer
    MLP.add(Dense(256, activation='relu')) # hidden layer 1
    MLP.add(Dense(256, activation='relu',kernel_regularizer=regularizers.l2(0.01) )) # hidden layer 2
    MLP.add(Dense(1, activation='sigmoid')) # output layer

    # summary
    # MLP.summary()

    # optimization
    MLP.compile(loss='binary_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])

    # train (fit)
    MLP.fit(train_X, train_Y, validation_data = (test_X, test_Y), 
        epochs=10, batch_size=48)

    # evaluate performance
    test_loss, test_acc = MLP.evaluate(test_X, test_Y,
                                    batch_size=48,
                                    verbose=0)
    

    # test
    print(fp)

    fp["Name"] = int(0)

    fingerprint = np.asarray(fp)
    
    # fingerprint

    fingerprint = np.reshape(fingerprint, (-1, 882))

    # fingerprint

    res = MLP.predict(fingerprint, verbose=0)
    print(res)

    # result = []
    # for r in res:
    #     if r[0] >= 0.5:
    #        result.append("active") 
    #     else:
    #         result.append("inactive")
    
    # res_df = pd.DataFrame(result)
    # return res
    if res >= 0.5:
        return "active"
    else:
        return "inactive"
