# -*- coding: utf-8 -*-
"""Molecular_descriptors_and_Fingerprinting [PART-3].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H7Njn0KpjKu5WCL4fNnQxz_x-eXYnpmr
"""

import pandas as pd
from .PaDel_Descriptor import fp_desc

# def mol_desc(final_bio_act):
def mdf():
    df3 = pd.read_csv('medi/Model/df_final_3c.csv')

    # df3

    selection = ['canonical_smiles', 'molecule_chembl_id']
    df3_selection = df3[selection]
    df3_selection.to_csv('medi/Model/molecule.smi', sep='\t', index=False, header=False)

    """Calculate fingerprint descriptors
    --------------------------------------

    **Calculate PaDEL descriptors** (already done in command line)

    Preparing X and Y Data Matrices
    ---------------------------------------



    **X data matrix**
    """


    #PADel

    df3_X = fp_desc(df3_selection)

    # df3_X = fp_desc('molecule.smi')
    # df3_X

    df3_X = df3_X.drop(columns=['Name'])
    # df3_X

    """**Y data matrix**"""

    df3_Y = df3['PIC50']
    # df3_Y

    """**Combining X and Y data matrices**"""

    dataset3 = pd.concat([df3_X, df3_Y], axis=1)
    # dataset3

    dataset3.to_csv('medi/Model/bioactivity_data_3c_pIC50_pubchem_fingerprints.csv')
        # return dataset3
